# https://dependabot.com/docs/config-file/
# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#about-the-dependabotyml-file
# https://dependabot.com/docs/config-file/validator
# @todo: should be synced
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "npm:"
      include: "scope"
    reviewers:
      - boitewitte
