# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
_extends: .github

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: |
  - $TITLE (#$NUMBER)

template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: "🚀 Features"
    labels:
      - enhancement
  - title: "🧷 Fixes"
    labels:
      - bug
  - title: "🧰 Maintenance"
    labels:
      - maintenance
  - title: "📖 Documentation"
    labels:
      - documentation

exclude-contributors:
  - 'dependabot'

exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
