name: 'Query Github Releases'
description: 'Query Github Releases'
author: Boite Witte <info@boite.nl>

runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: "purple"
  icon: "user"

inputs:
  latest:
    description: Get Only latest (time) Release
    required: true
    default: true
  prerelease:
    description: Get Prerelease
    required: true
    default: true
  draft:
    description: Get Draft Release
    required: true
    default: true

outputs:
  gh_output:
    description: 'The generated github action output'
