name: 'Query Github Releases'
description: 'Query Github Releases'
author: Boite Witte <info@boite.nl>

runs:
  using: 'node16'
  main: 'dist/action.js'
branding:
  color: "green"
  icon: "activity"

inputs:
  select:
    description: Which release do you want to retrieve? (latest, previous, oldest, max, min, specific release)
    default: latest
  prerelease:
    description: Get Prerelease
    default: false
  draft:
    description: Get Draft Release
    default: false
  exclude-draft:
    description: Exclude Draft Releases
    default: true
  range:
    description: Get Semver Versions from within a specific Range

outputs:
  id:
    description: The Release ID
  name:
    description: The name for the release
  tag_name:
    description: The tag name for the release
  body:
    description: Description of the Release
  url:
    description: The URL of the Release
