name: build-test-run

on:
  workflow_dispatch:
  # rebuild any PRs and main branch changes
  pull_request:
    branches: [$default-branch, main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches:
      - $default-branch
      - main
      - 'releases/*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build: # make sure we can build action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm run pack
      - name: test
        run: npm run test:coverage
      - name: run-action
        uses: ./
        id: run_action
        with:
          draft: true

      - name: log-action-output
        run: echo ${{steps.run_action.outputs.gh_output}}
