name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - $default-branch
      - main

jobs:
  administration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: check-version
        continue-on-error: true
        with:
          create-tag: false
      - name: PR labeling
        uses: srvaroa/labeler@v0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Version Label
        if: steps.check-version.outputs.previous-version != steps.check-version.outputs.current-version
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ (contains(steps.check-version.outputs.current-version, '-rc') && 'prerelease') || 'version' }}
