name: Release
on:
  push:
    branches:
      - $default-branch
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get current release
        id: current-version
        run: |
          echo "::set-output name=version::$(npm pkg get version | xargs)"
      - uses: ./
        name: Check if version "${{ steps.current-version.outputs.version }}" is released
        id: check-version
        with:
          exclude-draft: true
          prerelease: ${{ contains(steps.current-version.outputs.version, '-rc')}}
          release: ${{ !contains(steps.current-version.outputs.version, '-rc')}}
          select: ${{ steps.current-version.outputs.version }}
      - uses: release-drafter/release-drafter@v5.20.0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: ${{ steps.check-version.outputs.found == 'false' }}
          prerelease: ${{ contains(steps.current-version.outputs.version, '-rc') }}
          version: ${{ steps.current-version.outputs.version }}
          tag: ${{ steps.current-version.outputs.version }}
