name: Release
on:
  push:
    branches:
      - $default-branch
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: check-version
      - uses: release-drafter/release-drafter@v5.20.0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: ${{ steps.check-version.outputs.previous-version != steps.check-version.outputs.current-version }}
          prerelease: ${{ contains(steps.check-version.outputs.current-version, '-rc') }}
          version: ${{ steps.check-version.outputs.current-version }}
          tag: ${{ steps.check-version.outputs.tag }}
